repos:
  - repo: https://github.com/mineiros-io/pre-commit-hooks
    rev: v0.2.1
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
      - id: golangci-lint
      - id: phony-targets
      - id: markdown-link-check
